volumes:
  es_data:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # For a single-node cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set memory options for JVM
      - xpack.security.enabled=false # Disable security for easier setup
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
