volumes:
  postgres-data-volume:
  es_data:

services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: LuiCsf5LUikmnI7TGR
      POSTGRES_DB: stack_insights_postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      service.name: "postgres"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # For a single-node cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set memory options for JVM
      - xpack.security.enabled=false # Disable security for easier setup
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
