default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: LuiCsf5LUikmnI7TGR
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: stack_insight_development

test:
  <<: *default
  database: stack_insight_test

production:
  <<: *default
  database: stack_insight_production
  username: stack_insight
  password: <%= ENV["STACK_INSIGHT_DATABASE_PASSWORD"] %>
